version: '2'
volumes:
  doppelganger-mirrors:
    external: true
services:
  doppelganger:
    image: andrewslotin/doppelganger:1.1
    ports:
      - "8081:8081"
    # To get an access token go to https://github.com/settings/tokens,
    # create new token with following permissions:
    # - public_repo (or repo if you're going to mirror private repositories too)
    # - write:repo_hook
    # Copy the token and paste it as DOPPELGANGER_GITHUB_TOKEN=<GITHUB_TOKEN>
    # into .env file located in current directory. 
    env_file: .env
    # Generally it's a good idea to use a data volume to keep the changing parts outside.
    # This data volume can be then attached to another container running an SSH server, or
    # an HTTP server if you want to access your mirror via HTTP.
    volumes:
      - doppelganger-mirrors:/var/mirrors
